export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const GET_USERS_FAILED="GET_USERS_FAILED"
export const GET_USERS_LOADING="GET_USERS_LOADING"

export const DELETE_USERS_SUCCESS="DELETE_USERS_SUCCESS"
export const DELETE_USERS_FAILED="DELETE_USERS_FAILED"
export const DELETE_USERS_LOADING="DELETE_USERS_LOADING"

export const ADD_USER_SUCCESS="ADD_USER_SUCCESS"
export const ADD_USER_FAILED="ADD_USER_FAILED"
export const ADD_USER_LOADING="ADD_USER_LOADING"

export const EDIT_USER_SUCCESS="EDIT_USER_SUCCESS"
export const EDIT_USER_FAILED="EDIT_USER_FAILED"
export const EDIT_USER_LOADING="EDIT_USER_LOADING"

